version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: novel_app
    container_name: novel_app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: novel_postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: novel_volume
