version: '3.2'
services:
  app:
    image: son29032001/novel:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novel_app
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
