services:
  api:
    image: son29032001/novel
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novel_api
    restart: always
    ports:
      - 3334:3334
    env_file:
      - .env
